Feature/adding admin panel
devph-git/patient-medical-records pull request #4
Opened 2020-08-01 03:14 UTC by Vincexx

Guys pacheck HAHA if ever na may mali pakisabe nalang hehe

2020-08-29 11:44 UTC, DarwinBuelo requested changes

2020-08-29 11:44 UTC, DarwinBuelo commented on routes/web.php
> +    return view('admin.dashboard');
Bro nag try ako iaccess yung page na ito pero di ata gumagana

![image](https://user-images.githubusercontent.com/20288875/91636030-04ea1180-ea30-11ea-8f9f-22f80eb4b222.png)

2020-09-12 03:58 UTC, djma777 commented on routes/web.php
> +    return view('admin.dashboard');
@Vincexx

2020-09-24 02:31 UTC, djma777 commented
closing this issue since we've changed architecture.

2020-09-24 02:31 UTC, closed without merging